const BASE_URL = "http://localhost:8000/api";

const LOGIN_ENDPOINT = BASE_URL + "/auth/login";
const SIGNUP_ENDPOINT = BASE_URL + "/auth/register";
const GOOGLE_LOGIN_ENDPOINT = BASE_URL + "/auth/google-login";
const GOOGLE_SIGNUP_ENDPOINT = BASE_URL + "/auth/google-signup";
const GET_CUSTOMER_ENDPOINT = BASE_URL + "/customer";
const CREATE_SEGMENT_ENDPOINT = BASE_URL + "/segment";
const GET_SEGMENTS_ENDPOINT = BASE_URL + "/segment";
const CREATE_CAMPAIGN_ENDPOINT = BASE_URL + "/campaign";
const GET_CAMPAIGN_ENDPOINT = BASE_URL + "/campaign";

export {
  BASE_URL,
  LOGIN_ENDPOINT,
  SIGNUP_ENDPOINT,
  GOOGLE_LOGIN_ENDPOINT,
  GOOGLE_SIGNUP_ENDPOINT,
  GET_CUSTOMER_ENDPOINT,
  CREATE_SEGMENT_ENDPOINT,
  GET_SEGMENTS_ENDPOINT,
  CREATE_CAMPAIGN_ENDPOINT,
  GET_CAMPAIGN_ENDPOINT,
};
